config:
  data:
    contrast_type: reward
    data_dir: /shared/healthinfolab/datasets/ABCD/Irritability/WholeBrainTaskfMRI/UConn/data
    labels_csv: /shared/healthinfolab/datasets/ABCD/Irritability/WholeBrainTaskfMRI/UConn/subject_lists/CBCL_PLPH_m0m24_MID_n3705.csv
    threshold: 0.1
    use_absolute: true
  device:
    cuda_device: 0
    use_cuda: true
  imbalance:
    focal_gamma: 2.0
    monitor_metric: balanced_acc
    use_class_weights: true
    use_focal_loss: true
    use_oversampling: false
  model:
    dropout: 0.4
    gnn_type: GCN
    hidden_channels: 64
    num_layers: 3
    pooling: mean
  output:
    confusion_matrix_plot: confusion_matrix_{contrast_type}.png
    model_filename: brain_gnn_{contrast_type}_balanced.pt
    save_model: true
    training_history_plot: training_history_{contrast_type}.png
    verbose: true
  training:
    batch_size: 32
    epochs: 200
    learning_rate: 0.001
    patience: 50
    random_seed: 0
    test_size: 0.2
    val_size: 0.2
    weight_decay: 0.0005
confusion_matrix:
- - 0
  - 509
- - 0
  - 62
results:
  test_accuracy: 0.1085814360770578
  test_auc: 0.4658089866277964
  test_balanced_accuracy: 0.5
  test_f1: 0.19589257503949448
  test_loss: 0.2678864264759625
run_info:
  run_dir: /home/rif17002/honors_thesis/runs/2026-02-05_17-58-56
  run_name: 2026-02-05_17-58-56
  timestamp: 1770332336.5125363
